"""Resume-safe planning and execution helpers for the B8.0 ORFS pilot."""

from __future__ import annotations

import hashlib
import json
import os
import platform
import re
import shutil
import socket
import subprocess
import tempfile
import time
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Sequence


SCHEMA_VERSION = 1
PLATFORM = "sky130hd"
DESIGNS = ("aes", "chameleon", "gcd", "ibex", "jpeg", "microwatt", "riscv32i")
SEEDS = (42, 43)
SMOKE_DESIGNS = ("gcd", "aes", "ibex")
SMOKE_ACTIONS = ("A02", "A11", "A20")


@dataclass(frozen=True)
class Action:
    action_id: str
    place_density_lb_addon: float
    routing_layer_adjustment: float

    def as_dict(self) -> dict[str, Any]:
        return {
            "action_id": self.action_id,
            "place_density_lb_addon": self.place_density_lb_addon,
            "routing_layer_adjustment": self.routing_layer_adjustment,
        }


ACTIONS = tuple(
    Action(f"A{row}{column}", addon, adjustment)
    for row, addon in enumerate((0.00, 0.05, 0.10))
    for column, adjustment in enumerate((0.20, 0.35, 0.50))
)
ACTION_BY_ID = {action.action_id: action for action in ACTIONS}


@dataclass(frozen=True)
class RunSpec:
    stage: str
    design: str
    action: Action
    seed: int

    @property
    def run_id(self) -> str:
        return f"{self.design}__{self.action.action_id}__seed_{self.seed}"

    @property
    def flow_variant(self) -> str:
        return f"b8_{self.action.action_id.lower()}_s{self.seed}"

    def as_dict(self) -> dict[str, Any]:
        return {
            "run_id": self.run_id,
            "stage": self.stage,
            "platform": PLATFORM,
            "design": self.design,
            "action": self.action.as_dict(),
            "seed": self.seed,
            "flow_variant": self.flow_variant,
        }


def canonical_json(payload: Any) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def sha256_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def atomic_write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, delete=False
    ) as handle:
        handle.write(json.dumps(payload, indent=2, sort_keys=True) + "\n")
        temporary = Path(handle.name)
    temporary.replace(path)


def smoke_specs() -> list[RunSpec]:
    return [
        RunSpec("smoke", design, ACTION_BY_ID[action_id], 42)
        for design in SMOKE_DESIGNS
        for action_id in SMOKE_ACTIONS
    ]


def matrix_specs() -> list[RunSpec]:
    """Return a deterministic interleaving of design, seed, and action."""

    specs: list[RunSpec] = []
    for round_index in range(len(ACTIONS)):
        for design_index, design in enumerate(DESIGNS):
            for seed_index, seed in enumerate(SEEDS):
                action = ACTIONS[(round_index + design_index + seed_index * 3) % len(ACTIONS)]
                specs.append(RunSpec("matrix", design, action, seed))
    if len({spec.run_id for spec in specs}) != 126:
        raise AssertionError("Matrix schedule must contain 126 unique runs")
    return specs


def render_fastroute_tcl(action: Action, seed: int) -> str:
    """Use the supported ORFS FastRoute interface for adjustment and seed."""

    return (
        "# Generated by ADVLSI2 B8.0; do not edit.\n"
        "set_global_routing_layer_adjustment "
        "$::env(MIN_ROUTING_LAYER)-$::env(MAX_ROUTING_LAYER) "
        f"{action.routing_layer_adjustment:.2f}\n"
        f"set_global_routing_random -seed {seed}\n"
        "set_routing_layers -signal "
        "$::env(MIN_ROUTING_LAYER)-$::env(MAX_ROUTING_LAYER)\n"
    )


def git_head(root: Path) -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=root, text=True, capture_output=True, check=False
    )
    if result.returncode:
        raise RuntimeError(f"Cannot resolve ORFS commit at {root}: {result.stderr.strip()}")
    return result.stdout.strip()


def git_is_clean(root: Path) -> bool:
    result = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=root,
        text=True,
        capture_output=True,
        check=False,
    )
    return result.returncode == 0 and not result.stdout.strip()


def cpu_flags() -> set[str]:
    cpuinfo = Path("/proc/cpuinfo")
    if not cpuinfo.is_file():
        return set()
    match = re.search(r"^flags\s*:\s*(.*)$", cpuinfo.read_text(errors="ignore"), re.M)
    return set(match.group(1).split()) if match else set()


def host_record(threads: int) -> dict[str, Any]:
    return {
        "hostname": socket.gethostname(),
        "platform": platform.platform(),
        "machine": platform.machine(),
        "python": platform.python_version(),
        "cpu_count": os.cpu_count(),
        "threads": threads,
        "avx512f": "avx512f" in cpu_flags(),
    }


def frozen_protocol(
    *,
    orfs_root: Path,
    container_image: str,
    container_digest: str,
    deck_path: Path,
    threads: int,
    timeout_seconds: int,
    executor: str,
) -> dict[str, Any]:
    if not container_digest.startswith("sha256:"):
        raise ValueError("container_digest must be an immutable sha256:... digest")
    if not deck_path.is_file():
        raise FileNotFoundError(deck_path)
    if not (orfs_root / "flow" / "Makefile").is_file():
        raise FileNotFoundError(orfs_root / "flow" / "Makefile")
    if not git_is_clean(orfs_root):
        raise ValueError("The ORFS checkout must be clean before freezing the protocol")
    payload = {
        "schema_version": SCHEMA_VERSION,
        "phase": "B8.0",
        "platform": PLATFORM,
        "designs": list(DESIGNS),
        "actions": [action.as_dict() for action in ACTIONS],
        "seeds": list(SEEDS),
        "orfs": {
            "repository": "https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts.git",
            "commit": git_head(orfs_root),
            "root": str(orfs_root.resolve()),
        },
        "container": {"image": container_image, "digest": container_digest},
        "exact_deck": {"path": str(deck_path.resolve()), "sha256": sha256_file(deck_path)},
        "execution": {
            "executor": executor,
            "threads": threads,
            "timeout_seconds": timeout_seconds,
        },
        "host": host_record(threads),
    }
    payload["protocol_hash"] = sha256_bytes(canonical_json(payload).encode())
    return payload


def initialize_manifest(root: Path, protocol: dict[str, Any], stage: str) -> dict[str, Any]:
    if stage not in {"smoke", "matrix"}:
        raise ValueError(stage)
    protocol_root = root / protocol["protocol_hash"]
    manifest_path = protocol_root / "manifest.json"
    specs = smoke_specs() if stage == "smoke" else matrix_specs()
    if manifest_path.is_file():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        if manifest["protocol"] != protocol:
            raise ValueError("Existing manifest does not match the frozen protocol")
    else:
        manifest = {
            "schema_version": SCHEMA_VERSION,
            "phase": "B8.0",
            "protocol": protocol,
            "runs": {},
        }
    for index, spec in enumerate(specs):
        manifest["runs"].setdefault(
            spec.run_id,
            {**spec.as_dict(), "order": index, "status": "pending", "attempts": 0},
        )
    atomic_write_json(manifest_path, manifest)
    return manifest


def action_workspace(orfs_root: Path, protocol_hash: str, spec: RunSpec) -> Path:
    workspace = orfs_root / "flow" / ".b8_actionability" / protocol_hash / spec.run_id
    workspace.mkdir(parents=True, exist_ok=True)
    (workspace / "fastroute.tcl").write_text(
        render_fastroute_tcl(spec.action, spec.seed), encoding="utf-8"
    )
    return workspace


def build_flow_command(
    spec: RunSpec,
    *,
    orfs_root: Path,
    protocol_hash: str,
    threads: int,
    executor: str,
    container_image: str | None = None,
    container_digest: str | None = None,
    target: str | None = None,
) -> list[str]:
    workspace = action_workspace(orfs_root, protocol_hash, spec)
    relative_tcl = workspace.relative_to(orfs_root / "flow") / "fastroute.tcl"
    make_args = [
        "make",
        f"DESIGN_CONFIG=./designs/{PLATFORM}/{spec.design}/config.mk",
        f"FLOW_VARIANT={spec.flow_variant}",
        f"PLACE_DENSITY_LB_ADDON={spec.action.place_density_lb_addon:.2f}",
        f"FASTROUTE_TCL={relative_tcl.as_posix()}",
        f"OR_SEED={spec.seed}",
        f"GRT_SEED={spec.seed}",
        f"NUM_CORES={threads}",
    ]
    if target:
        make_args.append(target)
    if executor == "native":
        return make_args
    if executor == "docker-shell":
        if not container_image or not container_digest:
            raise ValueError("docker-shell requires a pinned image and digest")
        return [
            "env",
            f"OR_IMAGE={container_image}@{container_digest}",
            "util/docker_shell",
            *make_args,
        ]
    raise ValueError(f"Unsupported executor: {executor}")


def _run_logged(
    command: Sequence[str], cwd: Path, log_path: Path, timeout_seconds: int
) -> tuple[int, float, str | None]:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    started = time.monotonic()
    timeout_reason = None
    with log_path.open("w", encoding="utf-8") as log:
        log.write("COMMAND: " + " ".join(command) + "\n")
        log.flush()
        try:
            result = subprocess.run(
                list(command),
                cwd=cwd,
                stdout=log,
                stderr=subprocess.STDOUT,
                text=True,
                timeout=timeout_seconds,
                check=False,
            )
            return_code = result.returncode
        except subprocess.TimeoutExpired:
            return_code = 124
            timeout_reason = f"timeout after {timeout_seconds} seconds"
            log.write("\nB8_TIMEOUT\n")
    return return_code, time.monotonic() - started, timeout_reason


def _first_existing(paths: Iterable[Path]) -> Path | None:
    return next((path for path in paths if path.is_file()), None)


def parse_klayout_report(path: Path) -> dict[str, Any]:
    root = ET.parse(path).getroot()
    by_rule: dict[str, int] = {}
    for item in root.findall("./items/item"):
        category = (item.findtext("category") or "unknown").strip("'\"")
        multiplicity = int(item.findtext("multiplicity") or "1")
        by_rule[category] = by_rule.get(category, 0) + multiplicity
    return {"total": sum(by_rule.values()), "by_rule": dict(sorted(by_rule.items()))}


def build_klayout_command(
    *,
    executor: str,
    container_image: str,
    container_digest: str,
    final_gds: Path,
    deck: Path,
    report: Path,
) -> list[str]:
    arguments = [
        "klayout",
        "-b",
        "-rd",
        f"input={final_gds.as_posix()}",
        "-rd",
        f"report={report.as_posix()}",
        "-rd",
        "feol=true",
        "-rd",
        "beol=true",
        "-rd",
        "offgrid=true",
        "-r",
        deck.as_posix(),
    ]
    if executor == "native":
        return arguments
    if executor == "docker-shell":
        return [
            "env",
            f"OR_IMAGE={container_image}@{container_digest}",
            "util/docker_shell",
            *arguments,
        ]
    raise ValueError(executor)


def collect_orfs_artifacts(
    orfs_root: Path, spec: RunSpec, exact_report: Path | None = None
) -> dict[str, Any]:
    flow = orfs_root / "flow"
    base = Path(PLATFORM) / spec.design / spec.flow_variant
    results = flow / "results" / base
    reports = flow / "reports" / base
    logs = flow / "logs" / base
    final_gds = results / "6_final.gds"
    checkpoint = _first_existing(
        [results / "2_6_floorplan_pdn.odb", results / "2_floorplan.odb"]
    )
    metadata = _first_existing(
        sorted(reports.glob("metadata-*.json"), key=lambda path: path.stat().st_mtime, reverse=True)
    )
    exact = None
    exact_parse_error = None
    if exact_report and exact_report.is_file():
        try:
            exact = parse_klayout_report(exact_report)
        except (ET.ParseError, OSError, TypeError, ValueError) as error:
            exact_parse_error = f"{type(error).__name__}: {error}"
    return {
        "results_dir": str(results),
        "reports_dir": str(reports),
        "logs_dir": str(logs),
        "final_gds": str(final_gds) if final_gds.is_file() else None,
        "final_gds_sha256": sha256_file(final_gds) if final_gds.is_file() else None,
        "checkpoint": str(checkpoint) if checkpoint else None,
        "checkpoint_sha256": sha256_file(checkpoint) if checkpoint else None,
        "metadata": str(metadata) if metadata else None,
        "metadata_sha256": sha256_file(metadata) if metadata else None,
        "exact_klayout_report": str(exact_report) if exact_report and exact_report.is_file() else None,
        "exact_klayout_report_sha256": sha256_file(exact_report) if exact_report and exact_report.is_file() else None,
        "exact_klayout_drc": exact,
        "exact_klayout_parse_error": exact_parse_error,
    }


def execute_one(
    *,
    output_root: Path,
    protocol: dict[str, Any],
    spec: RunSpec,
    rerun_failed: bool = False,
) -> dict[str, Any]:
    protocol_root = output_root / protocol["protocol_hash"]
    manifest_path = protocol_root / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    record = manifest["runs"][spec.run_id]
    run_dir = protocol_root / spec.stage / spec.run_id
    if record["status"] == "complete" and completion_is_valid(record, run_dir):
        return record
    if record["status"] == "complete":
        record["status"] = "pending"
        record["failure_reason"] = "stale completion marker or artifact hash mismatch"
        atomic_write_json(manifest_path, manifest)
    if record["status"] == "failed" and not rerun_failed:
        return record

    orfs_root = Path(protocol["orfs"]["root"])
    executor = protocol["execution"]["executor"]
    if executor == "docker-shell" and not protocol["host"]["avx512f"]:
        raise RuntimeError(
            "Current official ORFS images may SIGILL at CTS on non-AVX-512 CPUs. "
            "Use a verified source-built image/native build or an AVX-512 host."
        )
    run_dir.mkdir(parents=True, exist_ok=True)
    command = build_flow_command(
        spec,
        orfs_root=orfs_root,
        protocol_hash=protocol["protocol_hash"],
        threads=int(protocol["execution"]["threads"]),
        executor=executor,
        container_image=protocol["container"]["image"],
        container_digest=protocol["container"]["digest"],
    )
    record.update(
        {
            "status": "running",
            "attempts": int(record["attempts"]) + 1,
            "command": command,
            "started_at_epoch": time.time(),
        }
    )
    atomic_write_json(manifest_path, manifest)
    return_code, flow_elapsed, failure_reason = _run_logged(
        command,
        orfs_root / "flow",
        run_dir / "flow.log",
        int(protocol["execution"]["timeout_seconds"]),
    )
    metadata_return_code = None
    metadata_elapsed = 0.0
    if return_code == 0:
        metadata_command = build_flow_command(
            spec,
            orfs_root=orfs_root,
            protocol_hash=protocol["protocol_hash"],
            threads=int(protocol["execution"]["threads"]),
            executor=executor,
            container_image=protocol["container"]["image"],
            container_digest=protocol["container"]["digest"],
            target="metadata",
        )
        metadata_return_code, metadata_elapsed, metadata_failure = _run_logged(
            metadata_command,
            orfs_root / "flow",
            run_dir / "metadata.log",
            int(protocol["execution"]["timeout_seconds"]),
        )
        failure_reason = failure_reason or metadata_failure

    preliminary = collect_orfs_artifacts(orfs_root, spec)
    exact_return_code = None
    exact_elapsed = 0.0
    exact_report = None
    if return_code == 0 and preliminary["final_gds"]:
        workspace = action_workspace(orfs_root, protocol["protocol_hash"], spec)
        deck_copy = workspace / "sky130A_mr.drc"
        shutil.copy2(Path(protocol["exact_deck"]["path"]), deck_copy)
        exact_report = workspace / "exact_drc.rdb"
        flow_root = orfs_root / "flow"
        exact_command = build_klayout_command(
            executor=executor,
            container_image=protocol["container"]["image"],
            container_digest=protocol["container"]["digest"],
            final_gds=Path(preliminary["final_gds"]).relative_to(flow_root),
            deck=deck_copy.relative_to(flow_root),
            report=exact_report.relative_to(flow_root),
        )
        exact_return_code, exact_elapsed, exact_failure = _run_logged(
            exact_command,
            flow_root,
            run_dir / "exact_drc.log",
            int(protocol["execution"]["timeout_seconds"]),
        )
        failure_reason = failure_reason or exact_failure
        if exact_report.is_file():
            shutil.copy2(exact_report, run_dir / "exact_drc.rdb")
            exact_report = run_dir / "exact_drc.rdb"

    artifacts = collect_orfs_artifacts(orfs_root, spec, exact_report)
    success = bool(
        return_code == 0
        and metadata_return_code == 0
        and exact_return_code == 0
        and artifacts["final_gds"]
        and artifacts["checkpoint"]
        and artifacts["metadata"]
        and artifacts["exact_klayout_report"]
        and artifacts["exact_klayout_drc"] is not None
    )
    elapsed = flow_elapsed + metadata_elapsed + exact_elapsed
    record.update(
        {
            "status": "complete" if success else "failed",
            "return_code": return_code,
            "metadata_return_code": metadata_return_code,
            "exact_drc_return_code": exact_return_code,
            "elapsed_seconds": elapsed,
            "phase_elapsed_seconds": {
                "flow": flow_elapsed,
                "metadata": metadata_elapsed,
                "exact_drc": exact_elapsed,
            },
            "failure_reason": failure_reason
            or (None if success else "flow failed or required artifacts are missing"),
            "artifacts": artifacts,
            "finished_at_epoch": time.time(),
        }
    )
    atomic_write_json(run_dir / "run.json", record)
    if success:
        (run_dir / "COMPLETE").write_text(canonical_json(record) + "\n", encoding="utf-8")
    atomic_write_json(manifest_path, manifest)
    return record


def completion_is_valid(record: dict[str, Any], run_dir: Path) -> bool:
    if not (run_dir / "COMPLETE").is_file():
        return False
    artifacts = record.get("artifacts", {})
    pairs = (
        ("final_gds", "final_gds_sha256"),
        ("checkpoint", "checkpoint_sha256"),
        ("metadata", "metadata_sha256"),
        ("exact_klayout_report", "exact_klayout_report_sha256"),
    )
    for path_key, hash_key in pairs:
        path_value = artifacts.get(path_key)
        expected = artifacts.get(hash_key)
        if not path_value or not expected:
            return False
        path = Path(path_value)
        if not path.is_file() or sha256_file(path) != expected:
            return False
    return True


def pending_specs(
    manifest: dict[str, Any],
    stage: str,
    rerun_failed: bool,
    protocol_root: Path | None = None,
) -> list[RunSpec]:
    records = sorted(manifest["runs"].values(), key=lambda item: item["order"])
    specs = []
    for record in records:
        if record["stage"] != stage:
            continue
        if record["status"] == "complete":
            run_dir = protocol_root / stage / record["run_id"] if protocol_root else None
            if run_dir is None or completion_is_valid(record, run_dir):
                continue
        if record["status"] == "failed" and not rerun_failed:
            continue
        specs.append(
            RunSpec(stage, record["design"], ACTION_BY_ID[record["action"]["action_id"]], int(record["seed"]))
        )
    return specs


def summarize_manifest(manifest: dict[str, Any], stage: str) -> dict[str, Any]:
    selected = [record for record in manifest["runs"].values() if record["stage"] == stage]
    counts = {status: sum(record["status"] == status for record in selected) for status in ("pending", "running", "complete", "failed")}
    return {
        "schema_version": SCHEMA_VERSION,
        "phase": "B8.0",
        "stage": stage,
        "protocol_hash": manifest["protocol"]["protocol_hash"],
        "planned_runs": len(selected),
        "status_counts": counts,
        "smoke_passed": stage == "smoke" and counts["complete"] == 9 and counts["failed"] == 0,
    }
